### ISSUE TITLE
QSIRecon output directory structure incorrect

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsirecon#127]
## Summary

The folder convention of QSIRecon is not correct (subject folder is not supposed to be there)
## Additional details

- QSIRecon version: 0.23.2
- Singularity version: `apptainer version 1.1.8-1.el7`

### What were you trying to do?
Run QSIRecon with `hbcd_scalar_map` workflow
### What did you expect to happen?
Have outputs appear directly in the `output_dir` argument
### What actually happened?
Running `ls */` in the `output_dir` directory leads to
```
derivatives:
qsirecon-DIPYDKI/  qsirecon-DSIStudio/	qsirecon-NODDI/  qsirecon-TORTOISE_model-MAPMRI/  qsirecon-TORTOISE_model-tensor/

logs:
CITATION.bib*  CITATION.html*  CITATION.md*  CITATION.tex*

sub-NDARINVM6PPNLBL:
log/
```

**Comment by tsalo** [comment]
I think that's the structure we discussed. The output_dir is a BIDS-derivatives dataset, with its own derivatives datasets (`derivatives/qsirecon-<suffix>`. Some outputs can end up in that initial BIDS-derivatives dataset, such as atlases warped to T1wACPC space.

**Comment by araikes** [comment]
Not having been a part of the discussion, outwardly the hierarchy doesn't make a ton of sense. Conceptually, all of the files are derivatives of `qsiprep` and the folders with the diffusion products (scalars, bundles, matrices) are not derivatives of the highest level of `output` (e.g. `/output/derivatives/qsirecon-TORTOISE/sub-xxx` is not derived from `/output/sub-xxx` in the same way that `/bids/derivatives/qsiprep/sub-xxx` is derived from `/bids/sub-xxx`).

That said, I do appreciate the separability so that you're not necessarily recomputing atlases across workflows as well as the overall organization on the `qsirecon-<suffix>` folders.

**Comment by dkp** [comment]
I like the separability of the pipelines (so qsirecon-<suffix>) as it prevents overwriting.  I was surprised that there was another layer of derivatives. Just my 2 cents.
